Display

<Display>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Idk just some pictures"
        Image:
            id: image
            source: root.display_image()
            size_hint: 1,6
        Button:
            text: "<<<"
            size_hint: .5,1
            on_release: root.go_back()
        Button:
            text: ">>>"
            size_hint: .5,1
            on_release: root.advance()